version: 0.0
os: linux
files:
  - source: target/demo-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/app

hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 180
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 180
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user
